import React, { useRef } from 'react';
import {
  Printer,
  Download,
  X,
  QrCode,
  ShieldCheck,
  Calendar,
  MapPin,
  Phone,
  Clock,
  Compass,
  FileText,
  Building2,
  Train,
} from 'lucide-react';

export default function OfflineTripPackModal({ isOpen, onClose, itinerary, bookingId = 'WNDR-2026-PASS' }) {
  const printRef = useRef(null);

  if (!isOpen || !itinerary) return null;

  const destination = itinerary.destination || 'Destination';
  const days = itinerary.days || 4;
  const people = itinerary.people || 2;
  const stay = itinerary.selected_stay || {};
  const transport = itinerary.selected_transport_outbound || itinerary.day_plans?.[0]?.transport || {};
  const safety = itinerary.safety_scorecard?.emergency_directory || {
    police: '112',
    women_helpline: '1091',
    hospital: '108',
  };

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadOfflineHtml = () => {
    const offlineHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Wandr Offline Trip Pack - ${destination}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; padding: 24px; color: #111; max-width: 800px; margin: 0 auto; line-height: 1.5; }
    .header { border-bottom: 2px solid #DA7756; padding-bottom: 12px; margin-bottom: 20px; display: flex; justify-content: space-between; align-items: center; }
    .badge { background: #fee2e2; color: #991b1b; padding: 4px 8px; border-radius: 4px; font-weight: bold; font-size: 12px; }
    .card { border: 1px solid #ddd; padding: 14px; border-radius: 8px; margin-bottom: 14px; background: #fafafa; }
    .title { color: #DA7756; font-size: 20px; font-weight: bold; margin-bottom: 4px; }
    .day { margin-bottom: 16px; padding: 12px; border-left: 4px solid #DA7756; background: #fff; }
    table { width: 100%; border-collapse: collapse; margin-top: 10px; font-size: 13px; }
    th, td { border: 1px solid #e5e5e5; padding: 8px; text-align: left; }
    th { background: #f3f3f3; }
  </style>
</head>
<body>
  <div class="header">
    <div>
      <div class="title">WANDR EMERGENCY OFFLINE TRIP PACK</div>
      <div>Booking Reference: <strong>${bookingId}</strong> · No Internet Required</div>
    </div>
    <div class="badge">OFFLINE VERIFIED</div>
  </div>

  <div class="card">
    <h3>Trip Summary: ${destination} (${days} Days · ${people} Travelers)</h3>
    <p><strong>Lodging:</strong> ${stay.name || 'Homestay'} (Host: ${stay.local_owner_name || 'Verified Host'})</p>
    <p><strong>Inbound Transit:</strong> ${transport.operator || 'Verified Transit'} (${transport.mode || 'Transit'}) · Dep: ${transport.departure || '07:00'} | Arr: ${transport.arrival || '15:00'}</p>
  </div>

  <div class="card" style="background: #fff3ed; border-color: #fdba74;">
    <h4 style="margin: 0 0 8px 0; color: #c2410c;">🚨 Local 24/7 Emergency Contacts for ${destination}</h4>
    <table>
      <tr><th>Service</th><th>Contact Number</th></tr>
      <tr><td>Local Police Control</td><td>${safety.police}</td></tr>
      <tr><td>State Women Helpline</td><td>${safety.women_helpline}</td></tr>
      <tr><td>Nearest Emergency Hospital</td><td>${safety.hospital}</td></tr>
      <tr><td>Nearest 24h Chemist</td><td>${safety.nearest_pharmacy || 'District 24/7 Pharmacy'}</td></tr>
    </table>
  </div>

  <h3>Day-by-Day Offline Schedule</h3>
  ${(itinerary.day_plans || []).map(dp => `
    <div class="day">
      <strong>Day ${dp.day} (${dp.date || 'Day schedule'})</strong> — Routine: ${dp.routine?.wake_up_time || '08:00'} wake-up
      <ul>
        ${(dp.activities || []).map(a => `<li><strong>${a.time || '10:00'}:</strong> ${a.name} (${a.duration_hours || 2}h)</li>`).join('')}
      </ul>
      <p style="font-size: 12px; color: #666; margin: 4px 0;">Meals: ${dp.meals?.map(m => m.suggestion).join(' · ') || 'Local food'}</p>
    </div>
  `).join('')}

  <p style="font-size: 11px; color: #888; text-align: center; margin-top: 30px;">
    Generated by Wandr Autonomous Tourism Agent · Smart India Hackathon 2026 · Saved for Offline Emergency Use.
  </p>
</body>
</html>`;

    const blob = new Blob([offlineHtml], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Wandr_Offline_Trip_Pack_${destination.replace(/\s+/g, '_')}_${bookingId}.html`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6 bg-slate-900/50 backdrop-blur-sm overflow-y-auto animate-in fade-in duration-150">
      
      {/* Modal Card */}
      <div className="w-full max-w-3xl bg-white text-slate-900 border border-slate-200/80 rounded-3xl overflow-hidden shadow-2xl flex flex-col max-h-[90vh]">
        
        {/* Modal Toolbar */}
        <div className="p-4 sm:p-5 border-b border-slate-100 flex items-center justify-between bg-slate-50/80">
          <div className="flex items-center gap-3">
            <div className="p-2.5 rounded-2xl bg-emerald-50 text-emerald-600 border border-emerald-200 shadow-2xs">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <h2 className="font-display text-base sm:text-lg font-bold text-slate-900">
                Offline Emergency Trip Pack & Pass
              </h2>
              <p className="text-xs text-slate-500 font-medium">
                Self-contained boarding pass with zero network dependency
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={handlePrint}
              className="px-3 py-1.5 rounded-xl bg-white hover:bg-slate-100 text-slate-700 border border-slate-200 text-xs font-semibold flex items-center gap-1.5 transition-colors cursor-pointer shadow-2xs"
              title="Print or save as PDF"
            >
              <Printer className="w-3.5 h-3.5 text-slate-600" />
              <span className="hidden sm:inline">Print / PDF</span>
            </button>

            <button
              type="button"
              onClick={handleDownloadOfflineHtml}
              className="px-3.5 py-1.5 rounded-xl bg-slate-900 hover:bg-slate-800 text-white text-xs font-semibold flex items-center gap-1.5 transition-colors shadow-xs cursor-pointer"
              title="Download standalone offline HTML file"
            >
              <Download className="w-3.5 h-3.5" />
              <span className="hidden sm:inline">Download HTML</span>
            </button>

            <button
              type="button"
              onClick={onClose}
              className="p-1.5 rounded-xl text-slate-400 hover:text-slate-800 hover:bg-slate-100 transition-colors cursor-pointer"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Printable Pass Body */}
        <div ref={printRef} className="p-5 sm:p-7 overflow-y-auto space-y-6 font-body">
          
          {/* Top Digital Boarding Pass Ticket */}
          <div className="p-5 sm:p-6 rounded-2xl bg-slate-50/70 border-2 border-dashed border-emerald-500/40 flex flex-col md:flex-row items-center justify-between gap-6 relative">
            <div className="space-y-3 flex-1">
              <div className="flex items-center gap-2">
                <span className="text-[10px] font-mono tracking-widest px-2.5 py-0.5 rounded-full bg-emerald-100 text-emerald-800 font-bold border border-emerald-200 uppercase">
                  Wandr Verified Offline Pass
                </span>
                <span className="text-xs text-slate-500 font-mono font-semibold">#{bookingId}</span>
              </div>

              <div>
                <h3 className="font-display text-2xl font-black text-slate-900 tracking-tight">
                  {destination}
                </h3>
                <p className="text-xs text-slate-500 mt-0.5 font-medium">
                  {days} Days Exploration · {people} {people > 1 ? 'Travelers' : 'Traveler'}
                </p>
              </div>

              <div className="grid grid-cols-2 gap-3 text-xs pt-2 border-t border-slate-200">
                <div>
                  <span className="text-slate-400 block text-[10px] font-bold uppercase tracking-wider">Lodging</span>
                  <span className="font-bold text-slate-800 block truncate">{stay.name || 'Local Stay'}</span>
                  <span className="text-[11px] text-slate-500">Host: {stay.local_owner_name || 'Verified Family'}</span>
                </div>
                <div>
                  <span className="text-slate-400 block text-[10px] font-bold uppercase tracking-wider">Inbound Transit</span>
                  <span className="font-bold text-slate-800 block truncate">{transport.operator || 'Express Transit'}</span>
                  <span className="text-[11px] text-slate-500">Dep: {transport.departure || '07:00'} · Arr: {transport.arrival || '15:00'}</span>
                </div>
              </div>
            </div>

            {/* Dynamic Vector SVG QR Code */}
            <div className="flex flex-col items-center justify-center p-3.5 rounded-2xl bg-white text-black shadow-sm border border-slate-200 flex-shrink-0">
              <svg width="120" height="120" viewBox="0 0 120 120" className="w-28 h-28">
                {/* Simulated High-Res Vector QR Code Pattern */}
                <rect width="120" height="120" fill="white" />
                {/* Position Marker Top-Left */}
                <rect x="8" y="8" width="30" height="30" fill="black" />
                <rect x="14" y="14" width="18" height="18" fill="white" />
                <rect x="19" y="19" width="8" height="8" fill="black" />
                {/* Position Marker Top-Right */}
                <rect x="82" y="8" width="30" height="30" fill="black" />
                <rect x="88" y="14" width="18" height="18" fill="white" />
                <rect x="93" y="19" width="8" height="8" fill="black" />
                {/* Position Marker Bottom-Left */}
                <rect x="8" y="82" width="30" height="30" fill="black" />
                <rect x="14" y="88" width="18" height="18" fill="white" />
                <rect x="19" y="93" width="8" height="8" fill="black" />
                {/* QR Data Matrix Bits */}
                <rect x="44" y="10" width="5" height="5" fill="black" />
                <rect x="54" y="10" width="10" height="5" fill="black" />
                <rect x="69" y="10" width="5" height="5" fill="black" />
                <rect x="44" y="20" width="10" height="5" fill="black" />
                <rect x="59" y="20" width="5" height="5" fill="black" />
                <rect x="44" y="30" width="5" height="5" fill="black" />
                <rect x="64" y="30" width="10" height="5" fill="black" />
                {/* Central Wandr Logo Mark in QR */}
                <rect x="48" y="48" width="24" height="24" rx="4" fill="#059669" />
                <circle cx="60" cy="60" r="6" fill="white" />
                {/* Lower Data Bits */}
                <rect x="44" y="80" width="8" height="5" fill="black" />
                <rect x="56" y="80" width="5" height="8" fill="black" />
                <rect x="66" y="80" width="12" height="5" fill="black" />
                <rect x="44" y="92" width="12" height="5" fill="black" />
                <rect x="60" y="92" width="18" height="5" fill="black" />
                <rect x="85" y="48" width="5" height="10" fill="black" />
                <rect x="95" y="48" width="12" height="5" fill="black" />
                <rect x="85" y="65" width="8" height="5" fill="black" />
                <rect x="100" y="65" width="10" height="8" fill="black" />
                <rect x="85" y="82" width="5" height="12" fill="black" />
                <rect x="95" y="82" width="8" height="5" fill="black" />
              </svg>
              <span className="text-[9px] font-mono tracking-wider font-bold text-slate-600 mt-1.5">
                SCAN FOR PASS
              </span>
            </div>
          </div>

          {/* Emergency Helplines Section */}
          <div className="p-4 sm:p-5 rounded-2xl bg-rose-50/70 border border-rose-200/80 space-y-2.5">
            <h4 className="text-xs font-bold text-rose-800 uppercase tracking-wider flex items-center gap-1.5">
              <span>🚨 Local 24/7 Emergency Dispatch for {destination}</span>
            </h4>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-2.5 text-xs">
              <div className="p-3 rounded-xl bg-white border border-rose-100 shadow-2xs">
                <span className="text-slate-400 block text-[10px] font-bold uppercase">Local Police</span>
                <span className="font-extrabold text-slate-900 text-sm">{safety.police}</span>
              </div>
              <div className="p-3 rounded-xl bg-white border border-rose-100 shadow-2xs">
                <span className="text-slate-400 block text-[10px] font-bold uppercase">Women Helpline</span>
                <span className="font-extrabold text-slate-900 text-sm">{safety.women_helpline}</span>
              </div>
              <div className="p-3 rounded-xl bg-white border border-rose-100 shadow-2xs">
                <span className="text-slate-400 block text-[10px] font-bold uppercase">Civil Hospital</span>
                <span className="font-extrabold text-slate-900 text-sm">{safety.hospital}</span>
              </div>
            </div>
          </div>

          {/* Day-by-Day Compact Offline Timeline */}
          <div className="space-y-3">
            <h4 className="text-xs font-bold text-slate-800 uppercase tracking-wider">
              Day-by-Day Offline Exploration Schedule
            </h4>

            <div className="space-y-2.5">
              {(itinerary.day_plans || []).map((dp) => (
                <div
                  key={dp.day}
                  className="p-4 rounded-2xl bg-slate-50/60 border border-slate-200 text-xs space-y-2"
                >
                  <div className="flex items-center justify-between text-slate-900 font-bold border-b border-slate-200/60 pb-1.5">
                    <span className="text-emerald-700">Day {dp.day} ({dp.date || 'Exploration'})</span>
                    <span className="text-[11px] text-slate-500 font-medium">
                      ⏰ {dp.routine?.wake_up_time || '08:00'} wake-up
                    </span>
                  </div>

                  {dp.transport && (
                    <div className="text-slate-700 text-[11px] font-medium">
                      🚆 Transit: {dp.transport.operator} ({dp.transport.departure} → {dp.transport.arrival})
                    </div>
                  )}

                  <div className="space-y-1.5 pt-0.5">
                    {(dp.activities || []).map((act, i) => (
                      <div key={i} className="text-slate-700 text-[11px] flex items-center justify-between">
                        <span>• <strong className="text-slate-900">{act.time || '10:00'}:</strong> {act.name}</span>
                        <span className="text-slate-400 font-medium">{act.duration_hours || 2}h</span>
                      </div>
                    ))}
                  </div>

                  {dp.meals && (
                    <div className="text-[11px] text-slate-500 pt-1 border-t border-slate-200/40">
                      🍴 Meals: {dp.meals.map((m) => m.suggestion).join(' · ')}
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>

        </div>

      </div>
    </div>
  );
}
